const q=new URLSearchParams(location.search),safe=(s,n=30)=>String(s||'').replace(/[<>]/g,'').trim().slice(0,n),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const name=safe(q.get('name')||'Alex',20),age=clamp(parseInt(q.get('age')||'7',10)||7,4,12),city=safe(q.get('destination')||'Rome',20),interest=safe(q.get('interest')||'dinosaurs',25),days=clamp(parseInt(q.get('days')||'4',10)||4,2,7);
const DB={
Rome:{flag:'🇮🇹',country:'Italy',icons:'🏛️ 🍕 ⛲',marks:['Colosseum','Trevi Fountain','Pantheon','Spanish Steps'],food:['pizza al taglio','gelato','supplì','pasta'],words:[['Ciao','Hello'],['Grazie','Thank you'],['Per favore','Please'],['Gelato','Ice cream']],facts:['The Colosseum is almost 2,000 years old.','Rome has hundreds of fountains.','Pizza al taglio is a classic Roman street snack.'],hunt:['a fountain','a red scooter','columns','a tiny balcony','a lion shape','an old stone','a gelato sign','a street musician','a church dome','a cobbled street','an Italian flag','a funny door'],quiz:[['Which landmark hosted ancient spectacles?','Colosseum','Big Ben','Eiffel Tower','Burj Khalifa'],['What frozen treat is Italy famous for?','Gelato','Pretzel','Waffle','Churros'],['What does Grazie mean?','Thank you','Hello','Water','Good night']]},
Paris:{flag:'🇫🇷',country:'France',icons:'🗼 🥐 🎨',marks:['Eiffel Tower','Louvre','Notre-Dame','Arc de Triomphe'],food:['croissant','crêpe','baguette','macaron'],words:[['Bonjour','Hello'],['Merci','Thank you'],['S’il vous plaît','Please'],['Oui','Yes']],facts:['The Eiffel Tower was completed in 1889.','The Louvre is one of the world’s largest museums.','The River Seine divides Paris.'],hunt:['a striped awning','a bicycle','a café table','a bridge','a croissant','a street artist','a French flag','flowers on a balcony','a metro sign','a statue','a fountain','a red chair'],quiz:[['Which famous tower is in Paris?','Eiffel Tower','Colosseum','Big Ben','Burj Khalifa'],['What does Merci mean?','Thank you','Hello','Please','Water'],['Which river runs through Paris?','Seine','Thames','Tiber','Danube']]},
London:{flag:'🇬🇧',country:'United Kingdom',icons:'🚌 👑 🎡',marks:['Big Ben','Tower Bridge','Buckingham Palace','London Eye'],food:['fish and chips','scone','pie','shortbread'],words:[['Hello','Hello'],['Thank you','Thank you'],['Please','Please'],['Cheers','Thanks / bye']],facts:['London’s Underground opened in 1863.','Big Ben is the nickname of the Great Bell.','London has many royal parks.'],hunt:['a red bus','a black cab','a royal symbol','a bridge','a phone box','a clock','a park bench','a double-decker','a performer','a crown','a river boat','a guard'],quiz:[['What colour are London buses?','Red','Yellow','Green','Purple'],['Which river runs through London?','Thames','Seine','Tiber','Nile'],['Which palace is linked to the monarch?','Buckingham Palace','Louvre','Pantheon','Sagrada Família']]},
Barcelona:{flag:'🇪🇸',country:'Spain',icons:'🧩 ⚽ 🌊',marks:['Sagrada Família','Park Güell','Casa Batlló','La Rambla'],food:['tapas','churros','pa amb tomàquet','crema catalana'],words:[['Hola','Hello'],['Gracias','Thank you'],['Por favor','Please'],['Sí','Yes']],facts:['Antoni Gaudí designed many famous Barcelona buildings.','Barcelona sits beside the Mediterranean Sea.','Park Güell is famous for colourful mosaics.'],hunt:['a mosaic','a palm tree','a football shirt','a balcony','a colourful tile','a market stall','a bicycle','a sea view','a sculpture','a Spanish flag','a curved building','a musician'],quiz:[['Which architect is linked to Barcelona?','Antoni Gaudí','Gustave Eiffel','Christopher Wren','Michelangelo'],['What decoration is common in Park Güell?','Mosaics','Ice sculptures','Wood cabins','Neon tubes'],['Which sea is beside Barcelona?','Mediterranean','Baltic','Black Sea','Red Sea']]},
Dubai:{flag:'🇦🇪',country:'United Arab Emirates',icons:'🏙️ 🐪 ✨',marks:['Burj Khalifa','Dubai Frame','Palm Jumeirah','Museum of the Future'],food:['dates','shawarma','luqaimat','hummus'],words:[['Marhaba','Hello'],['Shukran','Thank you'],['Min fadlak','Please'],['Na’am','Yes']],facts:['Burj Khalifa is the tallest building in the world.','Dubai sits beside the Arabian Gulf.','Dates are part of traditional Emirati hospitality.'],hunt:['a super-tall building','a palm tree','a gold sign','a fountain','a camel picture','a futuristic building','a boat','a date fruit','an Arabic sign','a desert colour','a UAE flag','a geometric pattern'],quiz:[['What is Burj Khalifa famous for?','It is extremely tall','It is underwater','It is a castle','It is a train station'],['Which landscape is close to Dubai?','Desert','Rainforest','Tundra','Glacier'],['What does Shukran mean?','Thank you','Hello','Please','Goodbye']]}}
const D=DB[city]||DB.Rome,icon={dinosaurs:'🦖',space:'🚀',animals:'🐾',football:'⚽',art:'🎨',mysteries:'🔎'}[interest]||'⭐';let seed=([...name+city+interest].reduce((a,c)=>a+c.charCodeAt(0),1)*2654435761)>>>0;const rnd=()=>((seed=(Math.imul(seed,1664525)+1013904223)>>>0)/4294967296),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const footer=`<div class="footer-note">KIDVENTURO • ${esc(name)} in ${esc(city)}</div>`,page=(n,body,cls='')=>`<section class="page ${cls}" data-page="${n}/25">${body}${footer}</section>`,head=(k,t,e)=>`<div class="title-row"><div><p class="kicker">${k}</p><h2>${t}</h2></div><div class="emoji">${e}</div></div>`,line=()=>'<div class="line"></div>',checks=a=>`<div class="checklist">${a.map(x=>`<div class="check"><span class="box"></span><span>${esc(x)}</span></div>`).join('')}</div>`,missions=a=>`<div class="missions">${a.map((x,i)=>`<div class="mission"><b>${i+1}</b><div>${esc(x)}</div></div>`).join('')}</div>`;
function wordSearch(){let words=shuffle([city,...D.marks,...D.food,interest].map(x=>x.toUpperCase().replace(/[^A-Z]/g,'')).filter(x=>x.length>2)).slice(0,7).map(x=>x.slice(0,10)),N=12,g=Array.from({length:N},()=>Array(N).fill(''));for(const w of words){for(let t=0;t<70;t++){let h=rnd()>.5,r=Math.floor(rnd()*(h?N:N-w.length+1)),c=Math.floor(rnd()*(h?N-w.length+1:N)),ok=true;for(let i=0;i<w.length;i++){let rr=r+(h?0:i),cc=c+(h?i:0);if(g[rr][cc]&&g[rr][cc]!==w[i])ok=false}if(ok){for(let i=0;i<w.length;i++)g[r+(h?0:i)][c+(h?i:0)]=w[i];break}}}const A='ABCDEFGHIJKLMNOPQRSTUVWXYZ';g=g.map(r=>r.map(x=>x||A[Math.floor(rnd()*26)]));return `<div class="word-grid">${g.flat().map(x=>`<span>${x}</span>`).join('')}</div><div class="word-bank">${words.map(x=>`<span>${x}</span>`).join('')}</div>`}
let P=[];
P.push(page(1,`<div class="brandline">KIDVENTURO</div><div class="cover-copy"><p class="kicker">MY PERSONALIZED TRAVEL ADVENTURE</p><h1>${esc(city)}</h1><p class="child">Made for ${esc(name)}, age ${age}</p><div class="chips"><span class="chip">${D.flag} ${D.country}</span><span class="chip">${days} day trip</span><span class="chip">${icon} Loves ${esc(interest)}</span></div></div><div class="cover-icons">${D.icons}</div>`,'cover'));
P.push(page(2,`${head('MEET THE EXPLORER','Explorer profile','🧒')}<div class="card mint"><p class="label">EXPLORER</p><h1>${esc(name)}</h1><p><strong>${D.flag} Destination:</strong> ${esc(city)} &nbsp; • &nbsp; <strong>Age:</strong> ${age} &nbsp; • &nbsp; <strong>Power:</strong> ${icon} ${esc(interest)}</p></div><p class="label" style="margin-top:12mm">I AM MOST EXCITED TO SEE…</p>${line()}<p class="label" style="margin-top:8mm">ONE THING I WANT TO LEARN…</p>${line()}<p class="label" style="margin-top:8mm">MY ADVENTURE NICKNAME…</p>${line()}`));
P.push(page(3,`${head('COUNTDOWN','Before we go','⏳')}<div class="two" style="margin-top:10mm"><div class="card yellow"><h1>${days}</h1><h3>days of adventure</h3><p>How do you feel? 😄 😮 🤩 😴</p></div><div class="card mint"><h3>My prediction</h3><p>Favourite place:</p>${line()}<p>Food I want to try:</p>${line()}</div></div><div class="card soft" style="margin-top:10mm"><h3>Explorer promise</h3><p>I promise to look up, look around, ask questions, try something new and help my family notice the little things.</p></div>`));
P.push(page(4,`${head('READY?','Pack like an explorer','🎒')}<p class="muted">Tick each item when it is packed.</p>${checks(['Kidventuro book','Pencil','Colouring pencils','Water bottle','Comfortable shoes','Small snack','Weather gear','Tickets / travel card','Camera with an adult','Curiosity','Good mood','Space for souvenirs'])}<div class="card mint" style="margin-top:12mm"><h3>${icon} Bonus mission</h3><p>Choose one tiny object connected to ${esc(interest)} as your travel mascot.</p></div>`));
P.push(page(5,`${head('ROUTE','Your mission map','🗺️')}<p class="muted">Write four memorable stops from your day.</p>${[1,2,3,4].map(i=>`<div class="rating"><strong>STOP ${i}</strong>${line()}<span>★</span></div>`).join('')}<div class="draw small">DRAW A SIMPLE MAP OF YOUR ROUTE</div>`));
let bingo=shuffle([['🚲','bicycle'],['🐕','dog'],['🎨','street art'],['🍦','ice cream'],['🌳','big tree'],['📷','camera'],['🎵','music'],['🗺️','map'],['☕','café'],['🚪','colourful door'],['🌸','flowers'],['🚌','bus'],['⛲','fountain'],['🏛️','old building'],[icon,interest],['🧢','funny hat']]);P.push(page(6,`${head('LOOK AROUND','Travel bingo','👀')}<p class="muted">Find four in a row — or fill the whole board.</p><div class="bingo">${bingo.map(([e,t])=>`<div><span><strong>${e}</strong>${esc(t)}</span></div>`).join('')}</div>`));
P.push(page(7,`${head('OBSERVE','I spy','🔭')}<div class="card mint"><h3>Find something…</h3><p>older than you • smaller than your hand • very high • beautifully designed • connected to ${esc(interest)}</p></div><div class="draw small">DRAW THE STRANGEST THING YOU FOUND</div><p class="label" style="margin-top:8mm">MOST SURPRISING THING</p>${line()}`));
P.push(page(8,`${head('CITY HUNT','Scavenger hunt','🔎')}<p class="muted">No rushing. The point is to notice ${esc(city)}.</p>${checks(D.hunt)}<div class="card yellow" style="margin-top:11mm"><strong>Hard mode:</strong> find something round, something noisy and something your family almost walked past.</div>`));
P.push(page(9,`${head('LANDMARK MISSION','Landmark detective','🏛️')}<p class="muted">Spot these places or learn one detail about each.</p>${missions(D.marks)}<p class="label" style="margin-top:10mm">DETECTIVE NOTES</p>${line()}${line()}${line()}`));
P.push(page(10,`${head('TASTE','Taste the city','🍴')}<p class="muted">Try it, spot it, or ask an adult what it is.</p>${missions(D.food.map(x=>'Food mission: '+x))}<div class="rating"><strong>Best bite</strong>${line()}<span class="stars">☆ ☆ ☆ ☆ ☆</span></div><div class="rating"><strong>Most unusual</strong>${line()}<span class="stars">☆ ☆ ☆ ☆ ☆</span></div>`));
P.push(page(11,`${head('LOCAL WORDS','Speak like a local','💬')}<div class="two" style="margin-top:10mm">${D.words.map(([a,b])=>`<div class="card soft"><p class="label">SAY</p><h2>${esc(a)}</h2><p>${esc(b)}</p></div>`).join('')}</div><div class="card mint" style="margin-top:10mm"><h3>Language mission</h3><p>Use one local word politely today. Which one?</p>${line()}</div>`));
P.push(page(12,`${head('PUZZLE','Word search','🔤')}<p class="muted">Words go left-to-right or top-to-bottom.</p>${wordSearch()}`));
P.push(page(13,`${head('SHAPES','Pattern mission','🧩')}<p class="muted">Architecture is a giant puzzle.</p>${checks(['circle','triangle','arch','spiral','repeating pattern','symmetry','three matching windows','a shape inside another shape'])}<div class="draw small">COPY THE COOLEST PATTERN YOU SEE</div>`));
for(let d=1;d<=4;d++)P.push(page(13+d,`${head('DAY '+d,'My travel journal','✏️')}<p class="label">BEST THING I SAW</p>${line()}${line()}<p class="label">SOMETHING NEW I LEARNED</p>${line()}${line()}<p class="label">SOMETHING THAT MADE ME LAUGH</p>${line()}<p class="label">MY MOOD: 😄 🤩 😴 😮 😋</p><div class="draw small">DRAW ONE MOMENT FROM DAY ${d}</div>`));
P.push(page(18,`${head('CREATE','Draw the city','🎨')}<p class="muted">Draw ${esc(city)} from memory. Make it yours.</p><div class="draw">YOUR VERSION OF ${esc(city.toUpperCase())}<br><br>Hidden challenge: add one tiny ${esc(interest)} detail.</div>`));
P.push(page(19,`${head('SEND A MEMORY','Write a postcard','💌')}<div class="card soft" style="margin-top:10mm"><p>Dear ____________________,</p><p>Today in ${esc(city)} I…</p>${line()}${line()}<p>The thing that surprised me most was…</p>${line()}${line()}<p>From,<br><strong>${esc(name)}</strong></p></div><div class="draw small">DRAW A POSTCARD PICTURE</div>`));
P.push(page(20,`${head('KEEP IT','Memory collector','🧠')}<div class="facts">${D.facts.map((x,i)=>`<div class="fact"><b>0${i+1}</b>${esc(x)}</div>`).join('')}</div><div class="card soft" style="margin-top:12mm"><h3>Add your own fact</h3><p>Ask an adult, guide or information board for one fact we did not include.</p>${line()}${line()}</div><div class="card mint" style="margin-top:10mm"><h3>Small memory, big story</h3><p>Write one smell, sound or tiny detail you want to remember in one year.</p>${line()}</div>`));
P.push(page(21,`${head('REVIEW','Rate the adventure','⭐')}<p class="muted">You are the travel critic.</p>${['The city','The food','The coolest landmark','Getting around','My Kidventuro missions'].map(x=>`<div class="rating"><strong>${x}</strong>${line()}<span class="stars">☆ ☆ ☆ ☆ ☆</span></div>`).join('')}<div class="card yellow" style="margin-top:10mm"><strong>Would you come back?</strong> YES / MAYBE / NO — because…${line()}</div>`));
P.push(page(22,`${head('TOGETHER','Family challenge','🤝')}<p class="muted">Choose at least three. Everyone takes part.</p>${missions(['Copy a statue pose in a family photo.','Let the youngest explorer choose the next snack.','Everyone names one detail nobody else noticed.','Find the best free view of the day.','Learn one local word together.','Choose a family landmark of the day.','Walk five minutes without looking at a screen.'])}`));
P.push(page(23,`${head('CAMERA','Photo missions','📷')}<div class="photo-grid"><div class="photo">${icon} Your travel mascot with a landmark</div><div class="photo">A tiny detail most tourists miss</div><div class="photo">The funniest family pose</div><div class="photo">Your favourite colour in the city</div></div>`));
P.push(page(24,`${head('TEST YOUR MEMORY','Final city quiz','🏆')}<div class="quiz">${D.quiz.map((z,i)=>`<div class="question"><strong>${i+1}. ${esc(z[0])}</strong><div class="answers">${shuffle(z.slice(1)).map(a=>`<span>${esc(a)}</span>`).join('')}</div></div>`).join('')}<div class="question"><strong>4. What was YOUR favourite place in ${esc(city)}?</strong>${line()}</div><div class="question"><strong>5. What would you tell another kid to look for?</strong>${line()}</div></div>`));
P.push(page(25,`<div class="brandline">KIDVENTURO</div><div class="seal">★</div><p class="kicker">OFFICIAL EXPLORER CERTIFICATE</p><h1>This certifies that</h1><h1 style="color:var(--orange);font-size:52px;margin-top:12mm">${esc(name)}</h1><p style="font-size:18px;margin-top:8mm">explored <strong>${D.flag} ${esc(city)}</strong> with curiosity, courage and excellent detective skills.</p><p style="margin-top:12mm">Special explorer power: <strong>${icon} ${esc(interest)}</strong></p><div class="signatures"><div class="signature">DATE</div><div class="signature">FAMILY EXPLORER SIGNATURE</div></div>`,'certificate'));
document.getElementById('book').innerHTML=P.join('');document.getElementById('toolbarTitle').textContent=`${name}'s ${city} Adventure`;document.getElementById('printBtn').onclick=()=>window.print();document.getElementById('backBtn').onclick=()=>history.length>1?history.back():location.href='index.html#create';